### ISSUE TITLE
If a big window is captured, can't save due to the preview

### ISSUE THREAD

**Issue by AnwarShah** [leafo/gifine#16]
If a big window is captured, can't save due to the preview window shown full size. This is bizarre! How can I save video or change options if controls aren't visible?

**Comment by Plandercozeron** [comment]
Project is running live?
Bump. High priority change-request.

**Comment by Migacz85** [comment]
Oh lord I have the same issue, Just add simple scroll bar and it should be fine.

**Comment by leafo** [comment]
pushed out a fix with fddc5e315c3d900bccf8ce4e5b7c6a619a365ad1

if you can run from master give it a shot

**Comment by Migacz85** [comment]
That's brilliant much better ! :-) :+1:
