### ISSUE TITLE
Tried a few seconds(10-20) of gif, produced ~140GB of garbage in tmp

### ISSUE THREAD

**Issue by ziaulrehman40** [leafo/gifine#22]
I tried to produce a gif of like 10-20 seconds, it got stuck on optimizing gif. And i left my pc running, when i came back after ~1 hour, it was still stuck there. SO i cancelled it and killed the process.

So far so good, than i started getting low disk warnings. When i analyzed i saw ~140GB of gifine folder in /tmp directory.

Something fishy happened, and as of its impact, this needs to be fixed. I am sorry, i had to delete the folder without analyzing(because my machine was stucking) so can't say what was in it. But i felt that i must at-least report it.

PS: #18 #20 and #14 are related.

**Comment by leafo** [comment]
It sounds like you perhaps left it recording for a long time by accident? 

The way this program works is by recording frames, 1 image at a time, to a file in tmp/. You then choose the frames at the end of the recording phase and encode it into a video of gif file. This is not designed for for long recording sessions as saving individual frames can be very disk usage intensive.

gifine also does not clean up the tmp files, that's your job (either on system restart, or when you're done). It's done this way so you can recover a session to re-encode at a later time using the tool to load a directory of frames.

Hope that helps
