### ISSUE TITLE
hard to choose delay and framerate so that it is original speed

### ISSUE THREAD

**Issue by freddii** [leafo/gifine#24]
for this program:
framerate=1/(delay*10/1000)=100/delay
=> delay=100/framerate

so the only useable combinations for original speed are:
delay=5 and framerate=20
delay=4 and framerate=25
delay=2 and framerate=50

**Comment by leafo** [comment]
Gif's have limited support for delay between frames. if you need something accurate then I recommend encoding to mp4.
