### ISSUE TITLE
Nothing happens when you click on "Record rectangle" without xrectsel installed

### ISSUE THREAD

**Issue by klaus7** [leafo/gifine#4]
Also no error is written to the command line.

On Ubuntu 16.04.

Everything works as expected after installing xrectsel. I just think you should write out an error message. Thanks for sharing your tool!

How to install xrectsel on ubuntu:

    git clone git@github.com:lolilolicon/xrectsel.git
    cd xrectsel/
    ./bootstrap 
    ./configure
    sudo make install

**Comment by ShevoPramide** [comment]
when i entered cd xrectsel/ >>>> gives me : no such directory

**Comment by leafo** [comment]
I also added support for https://github.com/naelstrof/slop which is a better rectangular selection tool imo

**Comment by fajaryanw** [comment]
when i clone git, it display error

`Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`
